[package]
name = "imageproc"
version = "0.16.0"
authors = ["theotherphil"]
license = "MIT"
description = "Image processing operations"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/imageproc"
exclude = ["examples/*.ttf"]

[dependencies]
conv = "0.3.1"
image = "0.20.0"
itertools = "0.7.0"
nalgebra = "0.16.0"
num = "0.2.0"
quickcheck = "0.6"
rand = "0.4.0"
rusttype = "0.5"
rayon = "1.0"

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
