[package]
name = "imageproc"
version = "0.17.0"
authors = ["theotherphil"]
edition = "2018"
license = "MIT"
description = "Image processing operations"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/imageproc"
exclude = ["examples/*.ttf"]

[dependencies]
assert_approx_eq = "1.0.0"
conv = "0.3.1"
image = "0.20.0"
itertools = "0.7.0"
num = "0.2.0"
rand = "0.4.0"
rusttype = "0.7"
rayon = "1.0"

[dev-dependencies]
quickcheck = "0.6"

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
